# CI properties — checked in
# Values use {{vault.*}} references resolved at task execution time

npmToken={{vault.operations-kv/ci/github.readPackagesToken}}
writeToken={{vault.operations-kv/ci/github.writePackagesToken}}
zbToken={{vault.operations-kv/ci/zerobias/org.zb-token}}
dispatchToken={{vault.operations-kv/ci/github.docsDeploymentToken}}
username={{vault.operations-kv/ci/github.username}}
