name: Pull Request Targeted to Dev Branch
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - ready_for_review
    branches:
      - dev

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  pull-request:
    if: github.repository == 'zerobias-org/vendor'
    uses: zerobias-org/devops/.github/workflows/content-pr-test-reusable.yml@main
    secrets: inherit
    with:
      test-timeout: 900
